[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
APP_URL = "https://qa-playwright.up.railway.app"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
NEXTAUTH_URL = "https://web-production-087e0.up.railway.app"
REDIS_URL = "${{Redis.REDIS_URL}}"
SESSION_SECRET = "${{SESSION_SECRET}}"
STRIPE_SECRET_KEY = "${{STRIPE_SECRET_KEY}}"
STRIPE_WEBHOOK_SECRET = "${{STRIPE_WEBHOOK_SECRET}}"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "${{NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}"
STRIPE_BASIC_PRICE_ID = "${{STRIPE_BASIC_PRICE_ID}}"
STRIPE_PRO_PRICE_ID = "${{STRIPE_PRO_PRICE_ID}}"
STRIPE_ENTERPRISE_PRICE_ID = "${{STRIPE_ENTERPRISE_PRICE_ID}}"
EMAIL_SERVER = "${{EMAIL_SERVER}}"
EMAIL_FROM = "${{EMAIL_FROM}}"
S3_BUCKET = "${{S3_BUCKET}}"
S3_REGION = "${{S3_REGION}}"
S3_ACCESS_KEY = "${{S3_ACCESS_KEY}}"
S3_SECRET_KEY = "${{S3_SECRET_KEY}}"
SLACK_WEBHOOK_URL = "${{SLACK_WEBHOOK_URL}}"